elb_name = 'Demo'
AWSAccessKey = 'AKIAVA2LEYH5JH7BPNUP'
AWSSecretKey = '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'
account_id = '123452793804'
elb_zones = ['us-east-1a', 'us-east-1b']
elb_listeners = [[80, 90, 'HTTP']]
s3_bucket_name = 'Demobbucket'
bucket_policy = 'public-read-write'
FunctionName = 'DemoTest'